version: '3.5'

services:
  abrirsessao:
    build: ./abrirsessao-service
    image: abrirsessao-service:0.0.1
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    command: java - jar *.jar
    networks:
      - postgres
      - default
    links:
      - pauta
  contabilizacao:
      build: ./contabilizacao-service
      image: contabilizacao-service:0.0.1
      ports:
        - "8081:8081"
      depends_on:
        - postgres
        - kafka
      command: java - jar *.jar
      networks:
        - postgres
        - default
        - broker
      links:
        - abrirsessao
        - kafka
  exiberesultado:
      build: ./exiberesultado-service
      image: exiberesultado-service:0.0.1
      ports:
        - "8087:8087"
      depends_on:
        - postgres
        - kafka
      command: java - jar *.jar
      networks:
        - postgres
        - default
      links:
        - kafka
  pauta:
      build: ./pauta-service
      image: pauta-service:0.0.1
      ports:
        - "8082:8082"
      depends_on:
        - postgres
      command: java - jar *.jar
      networks:
        - postgres
        - default
      external_links:
        - pautaservice

  votacao:
      build: ./votacao-service
      image: votacao-service:0.0.1
      ports:
        - "8085:8085"
      depends_on:
        - postgres
        - kafka
      command: java - jar *.jar
      networks:
        - postgres
        - default
        - broker
      links:
        - abrirsessao
        - kafka
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: votacao
      POSTGRES_PASSWORD: votacao
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - broker
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    hostname: broker
    networks:
          - broker
          - postgres
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://broker:29092,PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  postgres:
    driver: bridge
  broker:
    driver: bridge
  default:
    external:
      name: pautaservice

volumes:
  postgres:
  pgadmin:

