server:
  port: 8084
spring:
  application:
    name: abrirsessao-service
  datasource:
    password: votacao
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/sessao
    username: votacao
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
pauta:
  endereco:
    endpoint: "http://pauta:8082/v1/api/pauta/get/"
